//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputAction/NewInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NewInput"",
    ""maps"": [
        {
            ""name"": ""OnMove"",
            ""id"": ""d16730bd-0746-4758-938c-64a478cb87a9"",
            ""actions"": [
                {
                    ""name"": ""WASD"",
                    ""type"": ""Value"",
                    ""id"": ""30b22a76-75d0-477e-984a-0faa7db1aa79"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""36089e5f-9c70-4c26-b778-27bedde81249"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""29f0ba1b-ce4a-4202-b550-fa2975d2c71a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""aa67b948-90d2-4c07-8db1-55903af51255"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""02c1c577-cffc-4d3c-9b8c-8e2d51210e78"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b602dbcc-48fd-400c-b94b-d72c53926831"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""OnSprint"",
            ""id"": ""001d3432-2816-4fd8-9e51-5f0181c2deff"",
            ""actions"": [
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""c974f057-af7b-4687-88fe-2338e09a2bd1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3f8293af-7113-4de6-a310-ace8529c6e69"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OnDebug"",
            ""id"": ""c2ef0854-d720-4dee-a600-67e74a3c989e"",
            ""actions"": [
                {
                    ""name"": ""F3"",
                    ""type"": ""Button"",
                    ""id"": ""4871c4f9-bfa0-49dc-8362-7b5c7d2ec357"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""85078a32-8f10-4555-a7d2-7c28a8420e54"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""F3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OnInteraction"",
            ""id"": ""e25d8458-efee-462e-b1c1-6662149287ed"",
            ""actions"": [
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""ba59ffbd-2188-43d8-a85a-3f2aa9f9fef5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3f290e71-34c0-44e3-8af8-12d27f0720c9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OnCombatMode"",
            ""id"": ""25e63f00-0546-489f-90d3-1d9d01a5e1cf"",
            ""actions"": [
                {
                    ""name"": ""Combat"",
                    ""type"": ""Button"",
                    ""id"": ""64d0720b-a600-4d73-9867-0a16d38e633b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2acaec68-4fc0-4f9c-bb86-ed2ff66a4827"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""Combat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OnAttack"",
            ""id"": ""306495e6-9cad-4130-a192-ec0db59b7a09"",
            ""actions"": [
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""c9e4817d-036f-4d21-bc17-093926a076d4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a8bec943-2985-476e-b8cf-7e7ab8b4bfa5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OnInventory"",
            ""id"": ""60223830-9dc2-4ef1-95d5-14db69ad3863"",
            ""actions"": [
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""2d268c5c-9089-4138-80ea-20e0021e3cd0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e02c4fbd-a770-4e27-9eb5-acbabfa0fa9e"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard;touch"",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""keyboard"",
            ""bindingGroup"": ""keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""touch"",
            ""bindingGroup"": ""touch"",
            ""devices"": []
        }
    ]
}");
        // OnMove
        m_OnMove = asset.FindActionMap("OnMove", throwIfNotFound: true);
        m_OnMove_WASD = m_OnMove.FindAction("WASD", throwIfNotFound: true);
        // OnSprint
        m_OnSprint = asset.FindActionMap("OnSprint", throwIfNotFound: true);
        m_OnSprint_Run = m_OnSprint.FindAction("Run", throwIfNotFound: true);
        // OnDebug
        m_OnDebug = asset.FindActionMap("OnDebug", throwIfNotFound: true);
        m_OnDebug_F3 = m_OnDebug.FindAction("F3", throwIfNotFound: true);
        // OnInteraction
        m_OnInteraction = asset.FindActionMap("OnInteraction", throwIfNotFound: true);
        m_OnInteraction_Interaction = m_OnInteraction.FindAction("Interaction", throwIfNotFound: true);
        // OnCombatMode
        m_OnCombatMode = asset.FindActionMap("OnCombatMode", throwIfNotFound: true);
        m_OnCombatMode_Combat = m_OnCombatMode.FindAction("Combat", throwIfNotFound: true);
        // OnAttack
        m_OnAttack = asset.FindActionMap("OnAttack", throwIfNotFound: true);
        m_OnAttack_Attack = m_OnAttack.FindAction("Attack", throwIfNotFound: true);
        // OnInventory
        m_OnInventory = asset.FindActionMap("OnInventory", throwIfNotFound: true);
        m_OnInventory_OpenInventory = m_OnInventory.FindAction("OpenInventory", throwIfNotFound: true);
    }

    ~@NewInput()
    {
        UnityEngine.Debug.Assert(!m_OnMove.enabled, "This will cause a leak and performance issues, NewInput.OnMove.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_OnSprint.enabled, "This will cause a leak and performance issues, NewInput.OnSprint.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_OnDebug.enabled, "This will cause a leak and performance issues, NewInput.OnDebug.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_OnInteraction.enabled, "This will cause a leak and performance issues, NewInput.OnInteraction.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_OnCombatMode.enabled, "This will cause a leak and performance issues, NewInput.OnCombatMode.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_OnAttack.enabled, "This will cause a leak and performance issues, NewInput.OnAttack.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_OnInventory.enabled, "This will cause a leak and performance issues, NewInput.OnInventory.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnMove
    private readonly InputActionMap m_OnMove;
    private List<IOnMoveActions> m_OnMoveActionsCallbackInterfaces = new List<IOnMoveActions>();
    private readonly InputAction m_OnMove_WASD;
    public struct OnMoveActions
    {
        private @NewInput m_Wrapper;
        public OnMoveActions(@NewInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @WASD => m_Wrapper.m_OnMove_WASD;
        public InputActionMap Get() { return m_Wrapper.m_OnMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnMoveActions set) { return set.Get(); }
        public void AddCallbacks(IOnMoveActions instance)
        {
            if (instance == null || m_Wrapper.m_OnMoveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnMoveActionsCallbackInterfaces.Add(instance);
            @WASD.started += instance.OnWASD;
            @WASD.performed += instance.OnWASD;
            @WASD.canceled += instance.OnWASD;
        }

        private void UnregisterCallbacks(IOnMoveActions instance)
        {
            @WASD.started -= instance.OnWASD;
            @WASD.performed -= instance.OnWASD;
            @WASD.canceled -= instance.OnWASD;
        }

        public void RemoveCallbacks(IOnMoveActions instance)
        {
            if (m_Wrapper.m_OnMoveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnMoveActions instance)
        {
            foreach (var item in m_Wrapper.m_OnMoveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnMoveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnMoveActions @OnMove => new OnMoveActions(this);

    // OnSprint
    private readonly InputActionMap m_OnSprint;
    private List<IOnSprintActions> m_OnSprintActionsCallbackInterfaces = new List<IOnSprintActions>();
    private readonly InputAction m_OnSprint_Run;
    public struct OnSprintActions
    {
        private @NewInput m_Wrapper;
        public OnSprintActions(@NewInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Run => m_Wrapper.m_OnSprint_Run;
        public InputActionMap Get() { return m_Wrapper.m_OnSprint; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnSprintActions set) { return set.Get(); }
        public void AddCallbacks(IOnSprintActions instance)
        {
            if (instance == null || m_Wrapper.m_OnSprintActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnSprintActionsCallbackInterfaces.Add(instance);
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
        }

        private void UnregisterCallbacks(IOnSprintActions instance)
        {
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
        }

        public void RemoveCallbacks(IOnSprintActions instance)
        {
            if (m_Wrapper.m_OnSprintActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnSprintActions instance)
        {
            foreach (var item in m_Wrapper.m_OnSprintActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnSprintActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnSprintActions @OnSprint => new OnSprintActions(this);

    // OnDebug
    private readonly InputActionMap m_OnDebug;
    private List<IOnDebugActions> m_OnDebugActionsCallbackInterfaces = new List<IOnDebugActions>();
    private readonly InputAction m_OnDebug_F3;
    public struct OnDebugActions
    {
        private @NewInput m_Wrapper;
        public OnDebugActions(@NewInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @F3 => m_Wrapper.m_OnDebug_F3;
        public InputActionMap Get() { return m_Wrapper.m_OnDebug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnDebugActions set) { return set.Get(); }
        public void AddCallbacks(IOnDebugActions instance)
        {
            if (instance == null || m_Wrapper.m_OnDebugActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnDebugActionsCallbackInterfaces.Add(instance);
            @F3.started += instance.OnF3;
            @F3.performed += instance.OnF3;
            @F3.canceled += instance.OnF3;
        }

        private void UnregisterCallbacks(IOnDebugActions instance)
        {
            @F3.started -= instance.OnF3;
            @F3.performed -= instance.OnF3;
            @F3.canceled -= instance.OnF3;
        }

        public void RemoveCallbacks(IOnDebugActions instance)
        {
            if (m_Wrapper.m_OnDebugActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnDebugActions instance)
        {
            foreach (var item in m_Wrapper.m_OnDebugActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnDebugActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnDebugActions @OnDebug => new OnDebugActions(this);

    // OnInteraction
    private readonly InputActionMap m_OnInteraction;
    private List<IOnInteractionActions> m_OnInteractionActionsCallbackInterfaces = new List<IOnInteractionActions>();
    private readonly InputAction m_OnInteraction_Interaction;
    public struct OnInteractionActions
    {
        private @NewInput m_Wrapper;
        public OnInteractionActions(@NewInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interaction => m_Wrapper.m_OnInteraction_Interaction;
        public InputActionMap Get() { return m_Wrapper.m_OnInteraction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnInteractionActions set) { return set.Get(); }
        public void AddCallbacks(IOnInteractionActions instance)
        {
            if (instance == null || m_Wrapper.m_OnInteractionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnInteractionActionsCallbackInterfaces.Add(instance);
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
        }

        private void UnregisterCallbacks(IOnInteractionActions instance)
        {
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
        }

        public void RemoveCallbacks(IOnInteractionActions instance)
        {
            if (m_Wrapper.m_OnInteractionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnInteractionActions instance)
        {
            foreach (var item in m_Wrapper.m_OnInteractionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnInteractionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnInteractionActions @OnInteraction => new OnInteractionActions(this);

    // OnCombatMode
    private readonly InputActionMap m_OnCombatMode;
    private List<IOnCombatModeActions> m_OnCombatModeActionsCallbackInterfaces = new List<IOnCombatModeActions>();
    private readonly InputAction m_OnCombatMode_Combat;
    public struct OnCombatModeActions
    {
        private @NewInput m_Wrapper;
        public OnCombatModeActions(@NewInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Combat => m_Wrapper.m_OnCombatMode_Combat;
        public InputActionMap Get() { return m_Wrapper.m_OnCombatMode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnCombatModeActions set) { return set.Get(); }
        public void AddCallbacks(IOnCombatModeActions instance)
        {
            if (instance == null || m_Wrapper.m_OnCombatModeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnCombatModeActionsCallbackInterfaces.Add(instance);
            @Combat.started += instance.OnCombat;
            @Combat.performed += instance.OnCombat;
            @Combat.canceled += instance.OnCombat;
        }

        private void UnregisterCallbacks(IOnCombatModeActions instance)
        {
            @Combat.started -= instance.OnCombat;
            @Combat.performed -= instance.OnCombat;
            @Combat.canceled -= instance.OnCombat;
        }

        public void RemoveCallbacks(IOnCombatModeActions instance)
        {
            if (m_Wrapper.m_OnCombatModeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnCombatModeActions instance)
        {
            foreach (var item in m_Wrapper.m_OnCombatModeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnCombatModeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnCombatModeActions @OnCombatMode => new OnCombatModeActions(this);

    // OnAttack
    private readonly InputActionMap m_OnAttack;
    private List<IOnAttackActions> m_OnAttackActionsCallbackInterfaces = new List<IOnAttackActions>();
    private readonly InputAction m_OnAttack_Attack;
    public struct OnAttackActions
    {
        private @NewInput m_Wrapper;
        public OnAttackActions(@NewInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Attack => m_Wrapper.m_OnAttack_Attack;
        public InputActionMap Get() { return m_Wrapper.m_OnAttack; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnAttackActions set) { return set.Get(); }
        public void AddCallbacks(IOnAttackActions instance)
        {
            if (instance == null || m_Wrapper.m_OnAttackActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnAttackActionsCallbackInterfaces.Add(instance);
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
        }

        private void UnregisterCallbacks(IOnAttackActions instance)
        {
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
        }

        public void RemoveCallbacks(IOnAttackActions instance)
        {
            if (m_Wrapper.m_OnAttackActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnAttackActions instance)
        {
            foreach (var item in m_Wrapper.m_OnAttackActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnAttackActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnAttackActions @OnAttack => new OnAttackActions(this);

    // OnInventory
    private readonly InputActionMap m_OnInventory;
    private List<IOnInventoryActions> m_OnInventoryActionsCallbackInterfaces = new List<IOnInventoryActions>();
    private readonly InputAction m_OnInventory_OpenInventory;
    public struct OnInventoryActions
    {
        private @NewInput m_Wrapper;
        public OnInventoryActions(@NewInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenInventory => m_Wrapper.m_OnInventory_OpenInventory;
        public InputActionMap Get() { return m_Wrapper.m_OnInventory; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnInventoryActions set) { return set.Get(); }
        public void AddCallbacks(IOnInventoryActions instance)
        {
            if (instance == null || m_Wrapper.m_OnInventoryActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnInventoryActionsCallbackInterfaces.Add(instance);
            @OpenInventory.started += instance.OnOpenInventory;
            @OpenInventory.performed += instance.OnOpenInventory;
            @OpenInventory.canceled += instance.OnOpenInventory;
        }

        private void UnregisterCallbacks(IOnInventoryActions instance)
        {
            @OpenInventory.started -= instance.OnOpenInventory;
            @OpenInventory.performed -= instance.OnOpenInventory;
            @OpenInventory.canceled -= instance.OnOpenInventory;
        }

        public void RemoveCallbacks(IOnInventoryActions instance)
        {
            if (m_Wrapper.m_OnInventoryActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnInventoryActions instance)
        {
            foreach (var item in m_Wrapper.m_OnInventoryActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnInventoryActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnInventoryActions @OnInventory => new OnInventoryActions(this);
    private int m_keyboardSchemeIndex = -1;
    public InputControlScheme keyboardScheme
    {
        get
        {
            if (m_keyboardSchemeIndex == -1) m_keyboardSchemeIndex = asset.FindControlSchemeIndex("keyboard");
            return asset.controlSchemes[m_keyboardSchemeIndex];
        }
    }
    private int m_touchSchemeIndex = -1;
    public InputControlScheme touchScheme
    {
        get
        {
            if (m_touchSchemeIndex == -1) m_touchSchemeIndex = asset.FindControlSchemeIndex("touch");
            return asset.controlSchemes[m_touchSchemeIndex];
        }
    }
    public interface IOnMoveActions
    {
        void OnWASD(InputAction.CallbackContext context);
    }
    public interface IOnSprintActions
    {
        void OnRun(InputAction.CallbackContext context);
    }
    public interface IOnDebugActions
    {
        void OnF3(InputAction.CallbackContext context);
    }
    public interface IOnInteractionActions
    {
        void OnInteraction(InputAction.CallbackContext context);
    }
    public interface IOnCombatModeActions
    {
        void OnCombat(InputAction.CallbackContext context);
    }
    public interface IOnAttackActions
    {
        void OnAttack(InputAction.CallbackContext context);
    }
    public interface IOnInventoryActions
    {
        void OnOpenInventory(InputAction.CallbackContext context);
    }
}
